### ISSUE TITLE
production server?

### ISSUE THREAD

**Issue by gentooza** [consul/consul#1199]
Hi everybody, and congrats for this amazing project!

Finally I've got the app running under development mode in a vps running Debian wheezy. 
I had to tweak lot's of things I'll be glad to share in other issues if it can be useful for anybody else.

And now there is no docs about setting it under production.

My question, as I almost know nothing about rails apps, is: could I get it working by following some guides like this:?
- http://stackoverflow.com/questions/1949229/change-a-rails-application-to-production
- https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-passenger-and-apache-on-ubuntu-14-04

Or there is any really professional method anywhere?

Thanks a lot!

**Comment by voodoorai2000** [comment]
Hello @gentooza!

Thanks for your interest in Consul. 

Currently there are no production deployment docs (PRs are welcomed :sweat_smile:)
Our current stack is Apache + Unicorn + Postgres + RVM + Capistrano. Nginx might be simpler to configure than Apache. Instead of those guides we recommend these ones:

- https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rvm-on-ubuntu-16-04 (rvm)
- https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-unicorn-and-nginx-on-ubuntu-14-04 (nginx and unicorn)
- https://www.digitalocean.com/community/tutorials/deploying-a-rails-app-on-ubuntu-14-04-with-capistrano-nginx-and-puma (capistrano)

Let us know how it goes or if you have any other questions!

**Comment by gentooza** [comment]
great

In fact I used rvm also, so the guides I found didn't work (it seems passenger takes the 'official' (via apt-get) ruby version installed and not rvm's. giving some nice code errors in webpage)

But We don't use nginx either :-/, I'll try the guides to see what I can learn anyway.

Thanks!

**Comment by gentooza** [comment]
Hi, I think I've passenger correctly configured using rvm.
I've copied the whole consul folder inside a www-data folder, and I can see a simple index.html file stored in consul/public (I think it's what I have to do, to test permissions)

Could you help me with the changes needed in database.yml and secrets.yml to have it working in production mode?

thanks

pd: the guides didn't help. (ngingx and capistrano, unicorn... :-S)

**Comment by gentooza** [comment]
So, what is needed to make Consul running in production environment?
Some changes in database?
ssl?
sorry to ask again, but I'm sure we could create some more documentation about it also (as in configuration) :-D

**Comment by voodoorai2000** [comment]
Closed in favor #1778
