### ISSUE TITLE
User accounts verification

### ISSUE THREAD

**Issue by gentooza** [consul/consul#1255]
Hi consul community!

Is there any way to remove the user account verification? In our case consul is intended to behave as a forum to take proposals, but we don't care about where come from users but in participation.

If it's not possible, is there any other solution?
The padron API is useful in other towns?
Could an administrative rol verify manually users?
...

Thanks!

**Comment by gentooza** [comment]
ok, after lot of searching, I finnally parsed the calls to residence and sms in app/models/concerns/verification.rb:
```
  def residence_verified?
    #Joa's hand
    return true
    #
    residence_verified_at.present?
  end
```
```
  def sms_verified?
    #Joa's hand again
    return true
    #
    confirmed_phone.present?
  end
```
It's clearly a temporal solution I'l have to recheck every git pull, but it works.
**I think it could be nice to have options of security levels and checks in app**

**Comment by voodoorai2000** [comment]
Hello @gentooza!

If it's not possible, is there any other solution?
Sure, this is something we have been meaning to do.
Permissions are mainly decided in models/abilities and in some cases in the method votable_by? in the respective model. It would be great to abstract this logic so that it is easily configurable by an admin. PRs very welcomed :)

The padron API is useful in other towns?
Sure it is, it is being used in many other towns, but it also needs a nice refactoring to make it easier to configure.

Could an administrative rol verify manually users?
Yes, we have a role Manager, who has various screen to manually verify users. At the moment it is quite coupled with the implementation for Madrid, but any admin can view this section too.

Probably the most pragmatic way to deal with your situation is to temporarily override models/concerns/verification.rb in your custom folder models/custom/concerns/verification.rb

**Comment by gentooza** [comment]
Hi @voodoorai2000!

Ok, perfect!

Finally we are solving (more or less) our needs. Afterwards, when we finally publish the app and with the code public under the AGPL, we'll try to make this changes easier to maintain and keep them updated with your many consul improvements. 

If we learn enough to make things really work better we'll try to share our contributions.

thanks

**Comment by voodoorai2000** [comment]
Sounds great :)

Thank you @gentooza

**Comment by iamnotgroot2** [comment]
hello  consul community !
just wanted to follow up regarding this Issue, 
is there an easy way to bypass the residence / sms  verification ?
is there some kind of documentation on how to implement a custom residence verification process? (for a consul fork )
any help would be greatly apreciated :)

**Comment by zamuro** [comment]
There's a PR that needs to be verified in order to implement that functionality. https://github.com/consul/consul/pull/1896

**Comment by zamuro** [comment]
@voodoorai2000 Would you please assign this to me? If aforementioned PR gets approved, that would be a matter of extending the functionality to other verification methods.

**Comment by decabeza** [comment]
Already done on **Added setting on admin to skip user verification**  https://github.com/consul/consul/pull/2399 🎉
