### ISSUE TITLE
Allow admins to manage geozones

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1275]
When configuring forks, it would be useful to have an admin section with CRUD actions for geozones.

**Comment by amiedes** [comment]
I'll do this!

**Comment by voodoorai2000** [comment]
Awesome!

**Comment by amiedes** [comment]
I have a couple of questions about this:

* ¿What happens when the admin tries to rename a Geozone which already has users/proposals/debates assigned?  ¿Should it be forbidden? Renaming is not really a problem since the `geozone_id` which acts as link from proposals, etc. to geozones won't change.
* ¿What happens when the admin tries to delete a Geozone which already has users/proposals etc. assigned? If the deletion takes place this could result in users or proposals belonging to no district. I think this should definitely be forbidden unless there are still no proposals/users etc. in the database.

**Comment by amiedes** [comment]
I'm having trouble trying to add that red header and sidebar from the admin layout to the Geozones section. ¿How is it done?

This is how the other sections look:

![captura de pantalla 2016-12-04 a las 21 37 23](https://cloud.githubusercontent.com/assets/9287468/20869053/b1fffb40-ba6a-11e6-8ece-84f51ca2ffa0.png)


And this is mine currently:

![captura de pantalla 2016-12-04 a las 21 37 36](https://cloud.githubusercontent.com/assets/9287468/20869028/f03fc5d0-ba69-11e6-8781-ff938d41ae74.png)

**Comment by xuanxu** [comment]
+1 to renaming freely
+1 to deletion only posible if geozone has no user/proposals assigned

**Comment by xuanxu** [comment]
To get the administrator header/sidebar your controller should inherit from `<Admin::BaseController`, that way it will use the _admin_ layout

**Comment by amiedes** [comment]
Thanks a lot!

**Comment by amiedes** [comment]
I think this is ready. There is one thing I'd like to mention though: when checking that a geozone has no resources 'attached' when trying to delete it I decided to do it this way:

```ruby
# app/controllers/admin/geozones_controller.rb
safe_to_destroy = true

Geozone.reflect_on_all_associations.each do |association|
  attached_model = association.klass
  safe_to_destroy &= attached_model.where(geozone: @geozone).empty?
end

if safe_to_destroy
  @geozone.destroy
# etc.
```

To be able to do this I had to modify the `Geozone` model because it only had a `has_many :spending_proposals` association. I don't know if adding these new associations may have any side-effects in other parts of the application.

```
# app/models/geozone.rb
class Geozone < ActiveRecord::Base
  has_many :proposals
  has_many :spending_proposals
  has_many :debates
  has_many :users

  # etc.
end
```

The other way to achieve was to do something like this:

```ruby
safe_to_destroy = true

safe_to_destroy &= Proposal.where(geozone: @geozone).empty?
safe_to_destroy &= Debate.where(geozone: @geozone).empty?
safe_to_destroy &= SpendingProposal.where(geozone: @geozone).empty?
safe_to_destroy &= User.where(geozone: @geozone).empty?

if safe_to_destroy
  @geozone.destroy
else
  # ...
```

But I think its easier to remember to add a new relationship into de `Geozone` model when a new resource that is linked to a geozone is added to the application than to remeber to add a new `safe_to_destroy &= NewModel.where(geozone: @geozone).empty?` into the admin geozones controller.
