### ISSUE TITLE
Merge proposals

### ISSUE THREAD

**Issue by rochgs** [consul/consul#1283]
With a lot of users making proposals is easy two or more instances of the same request. It would be nice administrators could merge proposals with the same request (merging its supports).

**Comment by xuanxu** [comment]
Thanks for the suggestion @rochgs. 
Some time ago we thought about this option in the Madrid fork, but was discarded because it is not nice for a government to move user' supports from one proposal to another, even if they are similar. There should be also a mechanism to propose merges to authors and let them decide which one should be the removed one.

Instead we added the option for authors to retire a proposal in favor of another one, and the supporters will get a notification and email.

Anyway maybe is ok to have that feature for admins for other Consul users, so let's keep this issue open in case someone wants to contribute this feature.

**Comment by conatus** [comment]
It would be cool if the retire feature had a field where you can link to the "retired in favour of" proposal. And there would be a particular generic treatment for this.

While there is a text box, this would allow for things to feel like such and such a proposal was integrated into another proposal, composited with it and have the possibility of listing all proposals integrated into a proposal along the way.

**Comment by voodoorai2000** [comment]
@conatus we would love on include that idea in Consul. PRs-Welcome!

**Comment by decabeza** [comment]
This has been debated many times, but it is very complex, merging two proposals should have the acceptance of the people who supported them and not just the authors.

This part will be more or less solved thanks to the new functionality [Dashboard](https://github.com/consul/consul/tree/dashboard) that is being developed.

For the second comment, users can already withdraw their proposal by choosing the reason "Duplicated". 😌 

![screenshot 2019-02-26 at 16 07 36](https://user-images.githubusercontent.com/631897/53422929-ada15600-39e0-11e9-8a60-b9fcf49160d8.png)
