### ISSUE TITLE
HTML issues

### ISSUE THREAD

**Issue by jaimeiniesta** [consul/consul#1310]
Here's a report on 1,000 pages of decide.madrid.es showing HTML issues and some broken links:

https://rocketvalidator.com/s/935d255f-bb91-49d4-a9df-c908cbd71ec9/p

Solving these HTML issues is important for browser compatibility and accessibility :)

**Comment by decabeza** [comment]
Hi @jaimeiniesta! thanks for the report. 👍 

I just solving a lot of HTML issues here https://github.com/consul/consul/pull/1309

There are a few out of our control (in all pages) generated by **Piwik** and **Facebook campaign** script:
- `Error: Bad start tag in “p” in “head”.`
- `Error: Stray end tag “noscript”.`
- `Error: Bad value for attribute “src” on element “iframe”: Tab, new line or carriage return found.`
- `Error: Stray end tag “head”.`
- `Error: Start tag “body” seen but an element of the same type was already open.`

There are two more issues (appears many times, because it's each comment on page) generated by [initial-js gem](https://github.com/dgilperez/initialjs-rails) (I'm trying to resolve):

- `Stray end tag “img”.`
- `Element “img” is missing required attribute “src”.`

**Comment by jaimeiniesta** [comment]
Hey, we've recenly added evolution charts to the reports:

https://rocketvalidator.com/s/39eb9f04-5f40-4f8a-9bbf-25f9aa32bf0c/c

Good work on fixing those issues :+1:

**Comment by voodoorai2000** [comment]
Thank you @jaimeiniesta !
