### ISSUE TITLE
Configure RVM capistrano

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1363]
In every deploy capistrano checks the current ruby version and installs it if necessary in addition to installing bundler:

```
  before :starting, "rvm1:install:rvm"
  before :starting, "rvm1:install:ruby"
  before :starting, "install_bundler_gem"
```

To speed up deployment, we could:

* Upgrade Ruby 2.6, which includes bundler, and get rid of the `install_bundler_gem`
* Only run `rvm1:install:rvm` when the Ruby version we're trying to install isn't available

**Comment by javierm** [comment]
I've updated the issue with details about how we're planning to implement it.

IMHO by default we should keep the `install:ruby` task, in order to make it easier to everyone to upgrade Ruby when they need to. Maybe we could add an extra task that skips that step, so power users get faster deployment times :thinking:.
