### ISSUE TITLE
Thanks page after creating a proposal

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1474]
Now when user create a new proposal only appears a simple alert and the view: `proposal / show`

![new_proposal_alert](https://cloud.githubusercontent.com/assets/631897/24415408/ad0cb5e4-13e1-11e7-837d-2c99dcbb160a.png)

The idea is to create a new page before, inviting the user to share the new proposal, and for example add a link to a more information page to improve the campaign:

![new_proposal_page](https://cloud.githubusercontent.com/assets/631897/24415542/112daae2-13e2-11e7-877a-ed7a5226c09a.png)

**Comment by bertocq** [comment]
I think I'm going to adventure with this one as well.

Just to be clear upfront, I imagine this to be implemented by creating a `/proposals/:id/share` route/page that could be reusable in other scenarios (instead of a thank you one). And will hold that "¡Has creado una nueva propuesta!" only if you come from the creation action. If that doesn't sound like the idea just ping me :)

**Comment by bertocq** [comment]
@decabeza so far I've been able to get:

![screen shot 2017-05-30 at 14 40 14](https://cloud.githubusercontent.com/assets/983242/26585792/840c6ffc-454d-11e7-86a9-f2b0b30976d8.jpg)

Althought the `También puedes ver más información de como mejorar tu campaña.` text is not present because I'm not sure which url/path should be used on the link.. its a new page or an existing one?

Code is ready but I've to tackle 9 spec scenarios that are broken because of the change in behaviour after proposal is created, plus create new ones for this share page.

What do you think? :)

**Comment by decabeza** [comment]
Hi @bertocq! I like the idea of reuse the `/proposals/:id/share` url 🎉 

Don't worry about the link of "ver más información" it's only for Madrid's fork (https://decide.madrid.es/mas-informacion/kit-decide)

I think it's better maintain the text `Not now, go to my proposal` like a simple link instead a button. The important CTA in this page should be share the proposal. If you can change this detail and... send a PR! 👏

**Comment by bertocq** [comment]
@decabeza you're right, reverted from button to just a link 👍 

Also I've made the "ver más información" link a configurable Settings option using something like `Setting['proposal_improvement_url'] = 'more-information/proposal-improvement'`. On both seeds.rb and dev_seeds.rb files its will be defaulted to `nil`, so it won't be visible... only at those forks that give a valid value. I'll add specs to both scenarios.

So right now with those changes (and the `proposal_improvement_url` present) looks like:

![screen shot 2017-05-30 at 22 32 50](https://cloud.githubusercontent.com/assets/983242/26603899/c962bb5c-4588-11e7-9b79-7a4aa8fb7a46.jpg)

Only specs missing 😄  to go (apart from merging the PR you've already ✅ 'ed )

**Comment by bertocq** [comment]
Done! PR at: https://github.com/consul/consul/pull/1580

**Comment by voodoorai2000** [comment]
Awesome!
