### ISSUE TITLE
Migrate spending proposals to investments

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1593]
Complete the [rake task](https://github.com/consul/consul/blob/master/lib/migrate_spending_proposals_to_investments.rb) to migrate spending proposals to investments

**Comment by bertocq** [comment]
Some work done about this at madrid https://github.com/AyuntamientoMadrid/consul/pull/1059 but it needs to be bulletproof for consul:
- [ ] duplicated comments instead of moving them
- [ ] redirect from old spending proposal urls/paths to new budget investment ones (somehow storing the spending proposal id in the associated investment object to find which investment is being requested with the old url)
- [ ] avoid creating a investment if it already exists (the rake could somehow abort or fail, and we don't want to start from the beginning but be clear about which one failed to help fix it before restarting)

**Comment by bertocq** [comment]
Remember to include hotfix https://github.com/AyuntamientoMadrid/consul/commit/4e7608d8a9cdf0627369705a874db4faaa62572c

**Comment by javierm** [comment]
Closed via #3441 and #3569.
