### ISSUE TITLE
Upgrade to latest foundation-rails gem version

### ISSUE THREAD

**Issue by bertocq** [consul/consul#1673]
We're currently using version [6.2.4.0](https://github.com/consul/consul/blob/master/Gemfile#L38), but using latest [foundation-rails](https://github.com/zurb/foundation-rails) version (6.3.1.0 at the time of writing this issue) would be a great improvement

**Comment by decabeza** [comment]
Yeah, now in the Gemfile we hace specified this version `gem 'foundation-rails', '~> 6.2.4.0'` because it seems [Turbolinks and Foundation are not playing nice](https://github.com/zurb/foundation-rails/issues/177) and we have some errors.

Maybe it's time to upgrade and try if all it's working ok. 😉

**Comment by zamuro** [comment]
How critical is this? If there's nothing that needs to be fixed ASAP, I'd like to go with this one.

**Comment by bertocq** [comment]
As we researched about it, we think this should/will be done once consul has been upgraded to Rails 5... and for that effort the Polls push and some other stuff must firstly be completed. I'll remove the PR's-welcome label to avoid more deception, sorry

**Comment by decabeza** [comment]
Already done! Actually we use `gem 'foundation-rails', '~> 6.4.3.0'` 🎉
