### ISSUE TITLE
Enabled legislation process

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1674]
## Background

Now when creating a new legislation process in the admin section `admin/legislation/processes` you must specify the process dates, and if not is the current date appears on "Next processes" `/legislation/processes?filter=next`

## What

Sometimes the admins don't want show the process in "Next processes" menu.

## How

Add a "Enabled" checkbox on process dates (similar to Debate and Allegations phases) to allow hides the whole process.

![enabled_processes](https://user-images.githubusercontent.com/631897/27380025-ef014850-567d-11e7-8981-952ab6f1e716.jpg)

**Comment by bertocq** [comment]
I thought about this when doing the other "Enabled" buttons independently. But didn't took the time to ask @voodoorai2000 and @xuanxu about it.

What I did was to enclose in two simple ruby classes [`Legislation::Process::Phase`](https://github.com/consul/consul/blob/master/app/models/legislation/process/phase.rb) and [`Legislation::Process::Publication`](https://github.com/consul/consul/blob/master/app/models/legislation/process/publication.rb) the logic around the [four phases and publications](https://github.com/consul/consul/blob/master/app/models/legislation/process.rb#L24-L38)

So maybe treating the "main Process" as another `Legislation::Process:Phase` and moving  the [`status`](https://github.com/consul/consul/blob/master/app/models/legislation/process.rb#L48-L58) logic on to that class, we could get this clean and tidy. Also a boolean attribute `process_enabled` would be needed, like the ones used for other phase/publications (https://github.com/consul/consul/blob/master/db/schema.rb#L419-L422)

What do you think?

**Comment by voodoorai2000** [comment]
👌 +1

**Comment by xuanxu** [comment]
+1, and +1 to change attribute name to `visible`or `published`

**Comment by bertocq** [comment]
Yes @xuanxu it was previously "active" but I didn't quite seemed to me a good drescription of the action as enabling/disabling was easier to undestand for me. But its true that its mon-verb, and Published its way more descriptive.

So "Enabled" => "Published" +1 (maybe the database columns could keep the `_enabled` sufix, but adding another migration to rename them should be easy :) )

**Comment by voodoorai2000** [comment]
+1 to `published`

**Comment by entantoencuanto** [comment]
Hi, I'm taking a look to this issue, and I'm thinking about making some changes in the `legislation\processes_controller`, but I have some doubts:

- Is there a reason to not set in routes actions such `debate,` `draft_publication,` `allegations` or `result_publication` as member actions? Can I change this to have them as member actions?. In this way `load_and_authorize_resource` generates and looks for permissions on the instance variable `@process` instead of a collection of processes.
- Which behavior do you prefer?
  - Control access to not published processes using cancancan permissions? In this way authorized users as administrators can see processes, and normal users receive an alert message.
  - Or directly excluding not published processes from queries in the controller so that `ActiveRecord::RecordNotFound` errors are generated when trying to access them.

**Comment by bertocq** [comment]
Great to see you back @entantoencuanto 👏  😄 

### About point 1.
 I don't really see a good reason for how those 4 actions are used right now (at https://github.com/consul/consul/blob/master/app/views/legislation/processes/_key_dates.html.erb); I guess having them as member actions would make more sense... and having that load_and_authorize_resource improvement as well. But I'm not fully aware of the feature and the context when it was developed :( So maybe @xuanxu or @voodoorai2000 need to check as well.

### About point 2
 I suppose say this feature can be used in two scenarios:

**A- Temporarily unpublishing a Process for "who-knows-what-reasons"**

An alert message would make more sense than a 404, since the url could have been already published in Social Media or Emails.

**B- Creating a Process that is initially not published, so admins can fill all values and Publish it whenever they are ready.**

Unless we fix the path from using an `id` number on to a `slug` (actual example  `http://localhost:3000/legislation/processes/5/debate) I would go with 404, to prevent people from trying to find active but unpublished process... not that they could do much anyway. 

That said, seems like overkill to do two separate things... so for this scenario I would go with the alert as well. As drawbacks on scenario A would be worse with a 404, that here just giving an alert "Yes there is a Process with this id/slug, but its not published yet"

**Comment by voodoorai2000** [comment]
Closed via #1714
