### ISSUE TITLE
Customize the Verification method ?

### ISSUE THREAD

**Issue by fredhampton** [consul/consul#1912]
We are looking to use Consul for our Coop that has several thousand members.
Is there a way to customize the Verification method ?

Thanks

**Comment by zamuro** [comment]
Related to https://github.com/consul/consul/issues/1255

**Comment by taitus** [comment]
Hi @fredhampton 

Answering your question "Is there a way to customize the Verification method?"

To be able to "customize" the application code you can follow this guide [1]

Before customizing the code, you can review the documentation where a section has been added in order to configure the connection with the Remote Census [2]
And how you can configure the Local Census [3]

If the objective is to remove the verification, in the administration area in the section "Settings > Global Settings > Features" you can enable/disable the feature:
  - Skip user verification: This will disable user verification and all registered users will be able to participate in all processes

[1] https://docs.consulproject.org/docs/english-documentation/customization/models
[2] https://docs.consulproject.org/docs/english-documentation/features/census_configuration
[3] https://docs.consulproject.org/docs/english-documentation/features/local_census

**Comment by fredhampton** [comment]
Thanks so much !!!!!
