### ISSUE TITLE
Voting in a poll causes a validation error

### ISSUE THREAD

**Issue by periflo90** [consul/consul#1934]
Our team found an error in the polls. When selecting an answer, the application doesn't reflect the changes in the question and it's necessary to refresh the page in order to see the changes reflected.

I debugged it, and I narrowed the problem down to this particular line in ```app/controllers/polls/questions_controller.rb```

https://github.com/consul/consul/blob/e526d3b883311f3475a28b23404e772fbf2080e3/app/controllers/polls/questions_controller.rb#L22

The debug output said the following:

```
ActiveRecord::RecordInvalid (La validación falló: Document number Este usuario ya ha votado):
  app/models/poll/answer.rb:17:in `record_voter_participation'
  app/controllers/polls/questions_controller.rb:22:in `answer'
```
I hope I was of help.

**Comment by bertocq** [comment]
Thanks @periflo90 !! Currently we're getting the entire Poll feature refactored on Consul and also we're porting back some parts  from Madrid's consul fork since there it was almost fully completed. We'll revisit this issue once the effort is done to see if its still present or the refactor took it away. Thanks again for your reports 👍 ❤️

**Comment by zamuro** [comment]
If specs haven't changed, I'd like to take this one.

**Comment by voodoorai2000** [comment]
Sorry @zamuro, I forgot to assign myself this issue, almost got it :)
