### ISSUE TITLE
Check poll dates

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2025]
Possible issue? Double check this:

> Poll shows on interface (03/10/2017 - 05/10/2017) but on database starts_at: "2017-10-02 22:00:00", ends_at: "2017-10-04 22:00:00"

**Comment by iagirre** [comment]
I'll look at this.

**Comment by iagirre** [comment]
The contradiction between what is stored in DB and what is shown are generated because of the timezones.

Taken the given example, when admin generates a poll they set the start date at 03/10/2017 (only date), and the system is assuming that the timestamp (date + hour) is `03/10/2017 00:00:00`. That's OK.

The problem arrives when storing that timestamp. The DB column format is `timestamp without time zone`, that is, the timestamp in UTC. The difference between UTC and Spain's timezone (I took Spain because is the timezone where I am) is 2 hours in summer and 1 hour in winter. October is still summer (talking about timezones, I mean), so, `03/10/2017 00:00:00` in UTC will be `02/10/2017 22:00:00` (2 hours earlier, just the difference between timezones). For the dates after `29/10/2017` (when winter time starts), the stored timestamp will be `01/11/2017 23:00:00` (1 hour earlier), until summer time arrives, and so on.

I don't think this is an issue _per se_, because the dates are stored in a "neutral" value and they are shown in the correct timezone (the server's, I think).

**Comment by bertocq** [comment]
Thanks @iagirre for the great explanation! You're right its not an actual bug :) 👏
