### ISSUE TITLE
Fix in-app notifications

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2047]
What
===
- Fix in-app notifications

How
===
- Making sure when someone responds to your comment or creates a root comment, the in-app notification does not through an exception
- Check for the following commentables (debate, proposal, investment, poll and topic)

Note
===
Inform our worried users once this is fixed
https://decide.madrid.es/debates/5258-funcionan-los-mensajes-privados

**Comment by decabeza** [comment]
Close this one because on CONSUL all the notifications are working. 

Tested on **debates**, **proposals**, **budget investment** and **poll**:

- Create item with `user A`
- Create a root comment with `user A`
- Respond this comment with `user B`
- Create a new root comment with `user B`

There is no exceptions and the notification icon (and mailer) works correctly 😌 

_Note: currently there is no notifications for (proposals) topics, it seems there is a problem with comments NOT related with this issue, I open a new one for this._

I move this issue to Madrid's fork.
