### ISSUE TITLE
Comments on proposals topic

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2078]
What
===

When comment on a (proposal) topic `/communities/276/topics/1` the `Publish comment` button stay grey and it's necessary to refresh the page to see the new comment.

Also this new comments are no generating notifications for authors. 

Screenshot
===

<img width="313" alt="comment_a_topic" src="https://user-images.githubusercontent.com/631897/31733133-090437e2-b43b-11e7-8f81-bfdc236fd3ad.png">

**Comment by ortegacmanuel** [comment]
I'll take this.

**Comment by ortegacmanuel** [comment]
@decabeza hi! I'm working on this, and I have a doubt about the notification generation for authors of community topics. I'm on the master branch and in my tests the notification is generated but the problem is when the author clicks on the notification, when I click on the notification I get this error:

`undefined method `topic_url' `

![peek 20-10-2017 13-19](https://user-images.githubusercontent.com/413133/31818792-ebd45142-b599-11e7-9d26-8bab5e4e4e39.gif)

I want to confirm if this is the error you are referencing to on this issue.

I already identified the problem with the button, it's just a missing reference to the event object.

Thanks!

**Comment by decabeza** [comment]
Hi @ortegacmanuel this issue is about the problem with the button.

The notification maybe is related with (https://github.com/consul/consul/issues/2047) I thought there are no notifications for topics 😅  Could you make a PR (you can add `[WIP]` on title) so I can see the code and research! 🔍 

Thanks! 🙏

**Comment by ortegacmanuel** [comment]
@decabeza Done!

I'm also exploring why happens the `undefined method topic_url'` when clicking on a notification associated with a community topic. It seems to be related with the fact that on the `routes.rb` file the topics resource is nested inside the communities resource and this does not fits with why directory structure and namespaces the topic functionality files are put in. For example, the `Topic` model file is in the root models directory and not in a community subdirectory.

**Comment by decabeza** [comment]
Closed by #2090 and #2094 🎉
