### ISSUE TITLE
Failure when attaching a second document to a Proposal

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2171]
## Current Behaviour
If you create a Proposal with more than one document you'll get the following failure:

![screen shot 2017-12-11 at 11 26 24](https://user-images.githubusercontent.com/983242/33826708-2e306cb6-de66-11e7-898e-80621b1a5708.jpg)

## Expected Behaviour
Obviously not a crash 😅 , but a valid proposal with more than one document attached.

## Reasons behind crash
As far as I've researched, the problem is that all attached document  hidden `cached_attachment `  inputs on the Proposal creation form have the same value (from the first document) so as the form submission is processed the temp files are removed and when it tries to create the second attachment with the first attachment temp file... it doesn't exist anymore.

## Proposed solution path
I would:
- Find all involved specs (not sure if only `/spec/shared/features/nested_documentable.rb`) and increase coverage with an scenario that tries to add 3 attached documents
- Solve the issue at hand (not sure if js only or there's ruby involved)
- Try both specs and manual test

Update
===
We have received some complaints from users about this.
Remember to inform the appropriate people when it's fixes

**Comment by iagirre** [comment]
I'll go with this.

**Comment by iagirre** [comment]
As the issue sais, the problem starts with the name of the attached documents: they all have the exact same name, so, when you upload a second one, the first one is overwriten. I realized that this isn't only happening when you upload 2 files in the same documentable object; it also happens if you upload 1 file in one of them and this same user uploads another one in a different object (e.g. upload a file to Proposal 1, open Proposal 2 in another tab, upload another file and save proposal. Go to Proposal 1 tab, save it and get this error).

I've managed to solve the problem changing the hash_data that generates the file name:
```
  has_attached_file :attachment, url: "/system/:class/:prefix/:style/:hash.:extension",
                                 hash_data: ":class/:attachment/:id/:style/:updated_at",
                                             # insetad of ":class/:style"
                                 use_timestamp: false,
                                 hash_secret: Rails.application.secrets.secret_key_base
```

Note: It works with any hash_data that differs one from another.

The problem is that now I'm facing another error when dealing with cached elements (it doesn't delete them), so I'm trying to figure out if that solutions is the correct one.

**Comment by iagirre** [comment]
### The problem
As I said in the previous comment, if you generate a `hash_data` that is unique for each file uploaded the error disappears; the files are uploaded and saved for the documentable. So far, so good.

At this moment, the paperclip configuration is this:
```
has_attached_file :attachment, url: "/system/:class/:prefix/:style/:hash.:extension",
                               hash_data: ":class/:style",
                               use_timestamp: false,
                               hash_secret: Rails.application.secrets.secret_key_base
```

That means that the uploaded files will be stored temporarily in a path like `/system/<class>/cached_attachments/user/<user_id>/original/generated_hash.extension`. This generated_hash (the `:hash` interpolate in the url) is generated using `hash_data` and `hash_secret`. The hash_data value `":class/:style"` is translated to `"proposal/original"` (supposing we are uploading document to a proposal), and this is the same for ALL documents we upload in a proposal (even if it's another one or a new one). That is causing the identicalness of the document names, and this is the origin of the problem.

**What we need?** A `hash_data` that is unique for each document. OK, shall we use the paperclip default configuration: `"class/:attachment/:id/:style/:updated_at"`. That `updated_at` looks good, and yes, it generates a unique `hash_data` for each element. However, it gives us another error: this temp files are not been deleted when the files are stored in the final path (`public/system/<class>/attachments/<... some folders paperclip generates ...>/original/generated_hash.extension`).

_For the sake of knowledge, it's not an error like the above, with a visual crash. It's not deleting the files and they stay there forever, something that it's not desirable._

### My guess
Why is this happening? Because the `hash_data` used when storing the file is not the same as the one used when deleting the files. Having this callback in mind, executed after the document saves and in charge of deleting the files in cached_attachments:
```
def remove_cached_attachment
  document = Document.new(documentable: documentable,
                          cached_attachment: cached_attachment,
                          user: user)
  document.set_attachment_from_cached_attachment
  document.attachment.destroy
end
```

Each time the `hash_data` is used, both `:id` and `:updated_at` (or any other interpolation used) are taken from the object that owns the attachment (`document` in our case). So, the `id` will be the document objet's id and `updated_at` will be the `attachment_updated_at` attribute.

When a user uploads a file, a document object is generated to hold that attachment. This object is not persisted into the DB until the documentable object is saved (lets say proposal, for clarity), so, the `hash_data` generated for that first document will be something like: `"class/attachments/nil/original/2017-12-20 15:00:00"`. When user saves the proposal, the document is also saved. (I know that the `hash_data` is used at some point after saving, generating a value similar to `"class/attachments/15/original/2017-12-20 15:00:00"`, where id has a value other than nil, but I wasn't able to catch the exact moment :sweat:).

After everything is saved, it's delete time. The `remove_cached_attachment` generates a document and attaches the `cached_attachment`, BUT, when paperclip is trying to access the file, it generates the hash with a different data (it uses `id` and `updated_at`, but, as the new document is a different one, these values may change). `id` will be `nil`, this is not the problem; `updated_at` is what makes the hash different, because the `hash_data` for that document will be: `"class/attachments/nil/original/2017-12-20 15:03:45"`, causing a difference between hashes, and that leads to _"unable to find the file"_. There is not an error per se, but the app cannot find the file and, therefore, it doens't delete it when calling destroy.

_Side note: document.attachment always returns a paperclip attachment, but document.attachment.exists? says if the file actually exists on the filesystem. In this case, calling document.attachment.exists? in this remove function returned false, what means that the file doesn't exists. [Explanation](https://gist.github.com/kinopyo/2224867)_ 

### Alternatives I've tried and their problems
I've tried different combinations to generate the `hash_data` until I reached to this problem. Here are the variables I've tried and their problems:
- :id = it's nil for every new file (1st, 2nd ant 3rd documents), so it will generate the same hash.
- :updated_at = explained above. It changes for each new document.
- :filename = when saving the object it will have the original filename, but when removing it, the filename changes to the hash generated previously (the file that's been used is the chached one).
- custom interpolation using filenames = same problem as :filename

### Solutions that work
I think that the only solution I was able to make it work was using the raw filename, whitout using any hash. The "problem" with that is that the file won't have a name like "2a8198c7634ea3b8067b35ba3e96095ad13a4a30.pdf", but something like "proyecto_1.pdf", what breaks the URI Obfuscation (and I imagine that this isn't what we want).

**Comment by bertocq** [comment]
Fixed at master branch
