### ISSUE TITLE
Improve redirect after budget edit

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2276]
Background
===

When an admin edit a budget `/admin/budgets/N/edit` and clic on "Update Participatory budget" the page redirect to `/admin/budgets/N`

What we need
===

When an admin edit a budget and clic on "Update Participatory budget" redirect to `/admin/budgets`

**Comment by bertocq** [comment]
The requested behaviour seems a bit odd to me, and for sure not consistent with the rest of the app... what's the reason behind or the underlying requirement?

**Comment by decabeza** [comment]
@bertocq I think the better UX is return to the same url where you clic on a determinate action, for example, if the admin goes to `/admin/budgets/` see this screen:

![budget_admin](https://user-images.githubusercontent.com/631897/34682164-570bbf70-f49e-11e7-8053-f67c003a2a7f.png)

If clic on "Edit budget" (to change a description or a phase) and clic on "Update Participatory budget" the page redirect to `/admin/budgets/N` (the same view of "Edit headings groups") and its a little unexpected/weird.

Anyway this is a minor change, we/I need to work on improve this admin flows 😅

**Comment by bertocq** [comment]
🤔 I think the problem is that http://localhost:3000/admin/budgets/N isn't actually showing all the Budget details.. but the Budget's Groups and Headings! And that's the real break in consistency and conventions :( true that this needs more work to make it "easier to use"

👍  I'll send a PR that does requested changes to at least have that little improvement
