### ISSUE TITLE
Budget new "Information" phase

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2303]
Background
==

Now the budgets have these phases on admin:
- Draft budget **`NEW`** (https://github.com/consul/consul/pull/2296)
- Accepting projects
- Reviewing projects
- Selecting projects
- Valuating projects
- Show budget investment price **`NEW`** (https://github.com/consul/consul/pull/2296)
- Balloting projects
- Reviewing Ballots
- Finished budget

What we need
==

Include a new **"Information"** phase (after draft, before accepting): this phase shows all filled information (budget name, description, phases, groups, headings...) but does not have any links.

Screenshot
==

![budgets_show_info_phase](https://user-images.githubusercontent.com/631897/34823043-4d0f40aa-f6c9-11e7-991a-7a50dd7260c3.jpg)

**Comment by bertocq** [comment]
I'd wait until https://github.com/consul/consul/issues/2288 is completed or at least enough is there to be able to create a feature spec for the "Show info without links" condition. Otherwise adding a phase to budget is just 10 lines of code, but without being able to tests the condition, a second PR would be needed to use it and tests it

**Comment by iagirre** [comment]
I'll do this one.
