### ISSUE TITLE
Make Community & Communitable truly polymorphic

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2361]
Work on this issue was done on pull request #2771. Applying the changes on that pull request to our current master branch might be all we need to implement this refactoring.

We have so many `community.from_proposal?` around that its really hard to make a fourth model "communitable".

Most of the methods (if not all) at https://github.com/consul/consul/blob/master/app/helpers/communities_helper.rb should me moved into the concern or just dissapear

The relations as well doesn't quite seem right (Commuties table should have the communitable id & type columns instead of the Proposal / Investment ones..)

This is not an urgent refactor but we're seeing problems in production at Madrid because of non-existent proposals that have their associated community still around (that's another issue to be tackled at: https://github.com/consul/consul/issues/2360)

**Comment by javierv** [comment]
I'll have a look at this one.

**Comment by voodoorai2000** [comment]
Awesome!

**Comment by javierv** [comment]
I've opened #2771 with a very basic "quick and under pressure" :wink: refactoring. I'll continue working on this issue next week.

Here's my first bunch of questions regarding this issue:

* I see `Legislation::Proposal` includes `Communitable`, but I haven't found any references to communities there, nor to legislation proposals in communities. Is there something I'm missing?
* The I18n keys used in this section use the key `investment`. Other sections use `budget_investment`, and Active Record uses `budget/investment`. Although it would be easier to use `budget/investment` here, I've left the original `investment` key because I don't know the impact changing a key could have on the CONSUL community. Is it usually safe to change a translation key, or is it recommended not to do so?
