### ISSUE TITLE
Lots of issues when trying to install Consul on fresh Ubuntu 16.04 server

### ISSUE THREAD

**Issue by kabeza** [consul/consul#2391]
Hi
I have null knowledge of Ruby, PostgreSQL nor Docker, but followed the docs/guides in a newly fresh Ubuntu Server 16.04 and this is what I've got:

Problem installing pg 0.21.0
![imagen_008](https://user-images.githubusercontent.com/274856/35445288-ee2f7a28-028f-11e8-85e8-294063c08bcf.jpg)
Googled and solved by **sudo apt-get install -y libpq-dev**

**bin/rake db:create**
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'coffee-rails'
![imagen_011](https://user-images.githubusercontent.com/274856/35445381-351d3e7a-0290-11e8-85c8-9c34dc113258.jpg)
Googled and solved by **sudo apt-get install nodejs**

**bin/rake db:create**
warning: parser/current is loading parser/ruby23, which recognizes 2.3.5-compliant syntax, but you are running 2.3.2...
![imagen_012](https://user-images.githubusercontent.com/274856/35445462-6fd219fa-0290-11e8-8581-c3fc114d72fb.jpg)
_Googled but could not solve with rvm install ruby-2.4.1 nor rvm install ruby --latest_

Finally, I executed
**bundle exec rspec**
Got a lots of red Fs and then executed
**rails s**
But could not access the app.

As you can see in the image, I'm loading http://server's_IP:3000 and I'm getting the squid/firewall/proxy screen. I've added the exception, there's no UFW set on server, etc.
![imagen_015](https://user-images.githubusercontent.com/274856/35445762-64db3a58-0291-11e8-991f-055c7dfad515.jpg)

1) Maybe there's a config option in the app to set server's ip so it is not treated as localhost:3000 ?

2) I see all this setups a test environment. How can I set a production CONSUL server?

Thanks a lot in advance for any guidances/tips you can give me

**Comment by aitbw** [comment]
Hi @kabeza, thanks for your comments! I'm going to answer some of them in order:

1) The installation for `pg` failed because it expects PostgreSQL to be already installed, as mentioned on the [README](https://github.com/consul/consul/blob/master/README.md) and the [Installation guide](https://consul_docs.gitbooks.io/docs/content/en/getting_started/prerequisites/linux.html)

2) We must have missed that one, we **do** need to specify a NodeJS runtime is needed (to compile the assets). I recommend handling this with [n](https://github.com/tj/n)

3) Yes, we're aware of that one but haven't found a solution yet 😕

4) Could you please elaborate further on which tests failed? Some of them tend to fail randomly (especially on Travis, see #2129)

Re: Accessing the app on a server, maybe @voodoorai2000 or @bertocq can help?

Cheers!

**Comment by kabeza** [comment]
Hi @aitbw 
1. Yes, I've gone through all pre-requisites and installed PostgreSQL before running that
2. Great
3. OK
4. How can I capture all those? Which command(s)?

Thanks again

**Comment by aitbw** [comment]
🤔 

As far as I know, on Ubuntu Server you need to **explicitly install** the packages you need (this to keep your server as lightweight as possible); maybe that's why the `bundle install` command failed at first

For the failing specs, screenshots with the failures and the reasons they failed will do for now :)

**Comment by kabeza** [comment]
@aitbw 

> For the failing specs, screenshots with the failures and the reasons they failed will do for now :)

Sorry
Please tell me how to capture all the failing specs, so I can post the output here

**Comment by aitbw** [comment]
@kabeza run the `bundle exec rspec` command again and get a screenshot of all the failures, then post it here

**Comment by kabeza** [comment]
Hi @aitbw sorry for delay
I've been searching a place (like pastebin) to upload the resulting file for the command, but could not find any site that allows 6mb txt file upload.
So here it is. Hope it was uploaded fine

[prueba1.txt](https://github.com/consul/consul/files/1677895/prueba1.txt)

**Comment by aitbw** [comment]
Hello again @kabeza, don't worry about it :)

The tests failed because they're dependent on [PhantomJS](http://phantomjs.org/) and the executable is not found on your PATH (i.e.: it's not installed)

Install it through your package manager or directly from the PhantomJS website, then run `bundle exec rspec --only-failures` and that should get you all the previously failing specs green 😄

**Comment by kabeza** [comment]
Hi @aitbw 
I could install PhantomJS by following this mini-tutorial
https://gist.github.com/telbiyski/ec56a92d7114b8631c906c18064ce620
Then executed
`bundle exec rspec --only-failures`

And finally got a 1.3 mb file output instead 6.3mb file

Hope you can get something useful... thanks a lot again

[prueba2.txt](https://github.com/consul/consul/files/1681545/prueba2.txt)

**Comment by aitbw** [comment]
Anytime, @kabeza :) Don't forget to install `ImageMagick` so you can get the full spec suite failure-free

**Comment by kabeza** [comment]
Great! I've got a 4,9kb file output
[prueba3.txt](https://github.com/consul/consul/files/1681700/prueba3.txt)

Now please lemme ask you some final questions

1) Do you see any fatal error that would not allow us to begin working?

2) I'm having some strange behaviour. Server's ip is 10.x.x.x (big govt lan). When I execute `rails s` it opens the server in port 3000, but I cannot access through http://10.x.x.x:3000
I tracert server from my machine, i don't get any jumps. It is in the same network. Direct.
I telnet 10.x.x.x 3000 and cannot access or get connection refused
I login again to terminal in 10.x.x.x and do telnet 127.0.0.1 3000 and it connects
No UFW nor any kind of firewall set/installed on 10.x.x.x server
![imagen_018](https://user-images.githubusercontent.com/274856/35624700-78ad0aee-066e-11e8-8c0f-22d50a004af3.jpg)

3) Which are the next steps to follow in case I want to go in production? I mean, to have the web server as service, leave it running in port 80, etc.?

Thanks a lot again

**Comment by voodoorai2000** [comment]
Hi @zenny!

We now have an automated installer to setup CONSUL in a Production environment 🎉 
Let's move the conversation to the [Installer's repo](https://github.com/consul/installer) 😌
