### ISSUE TITLE
Installing Consul App in a Plesk environment

### ISSUE THREAD

**Issue by GianniPDF** [consul/consul#2485]
After activating NodeJS, the Plesk administration asks for a app.js but i can not find one in the source files of the Consul app, there should be an app.js file somewhere?

Another question, the Consul app can run under Ruby 2.3.6? And under Passenger® web server?

And please, update the installation guide that NodeJS is needed as said it here https://github.com/consul/consul/issues/2391

**Comment by aitbw** [comment]
Hi @GianniPDF! I'm not aware of how Plesk works but you don't need an `app.js` anywhere for CONSUL (unless you have implemented a modern JS workflow for your fork and it would be a `index.js` file instead); the only JavaScript-related thing you need when working with CONSUL is a NodeJS runtime in order to compile the assets.

We haven't tested CONSUL under Ruby 2.3.6 but since it's a minor update, it should work without problems. Regarding Passenger, maybe @voodoorai2000 or @bertocq can shed some light on this? :thinking:

And thanks for the heads-up on the README update :pray: I'll make a PR right away :wink:

**Comment by GianniPDF** [comment]
Well, it works on Ruby 2.3.6 and with Passenger® web server. I can not give too much details becuase the Plesk app does a lot of the configuration for me but i guess i can figure out more searching through the files. Thank you

**Comment by bertocq** [comment]
Sorry @GianniPDF for the late response. We don't have any experience using Plesk/Passenger, we use internally managed servers at Madrid's fork and we've seen Consul work on a Heroku but nothing more. It would be an awesome contribution to the project if you could explain the steps it took for you to deploy Consul with those technologies :) (At least as a comment to this issue so we can close it, best would be at the official docs https://github.com/consul/docs/) Thanks!

**Comment by GianniPDF** [comment]
Ok, let me gather the data and i will post it soon

**Comment by javierm** [comment]
Closing since the README was updated, we now use Ruby 2.4.9, and it looks like the original questions have been answered.
