### ISSUE TITLE
Datepicker months is not localized

### ISSUE THREAD

**Issue by PierreMesure** [consul/consul#2638]
![capture d ecran 2018-05-22 a 16 35 30](https://user-images.githubusercontent.com/7223028/40369609-9d904886-5dde-11e8-8a6f-0377277e1c8d.png)

Not sure how I would go to fix it. The datepicker months are in Spanish even though the English translation is present.

**Comment by decabeza** [comment]
Hi @PierreMesure this issue is related to [jQuery Datepicker widget](https://jqueryui.com/datepicker/) we use on CONSUL.

You can add [any i18n of this list](https://github.com/jquery/jquery-ui/tree/master/ui/i18n)

For example if you add `//= require jquery-ui/i18n/datepicker-en-GB` on `app/assets/javascripts/application.js:17` the calendar appears on english. Should appear on current locale (not always in the same language).

![en_calendar](https://user-images.githubusercontent.com/631897/40377157-7f453532-5df0-11e8-89ed-5b9236a4c67b.png)

Feel free to send a PR! 😉

**Comment by PierreMesure** [comment]
Interesting! I'll try to add this line for all the languages I support to see if it actually changes when I change the locale. But would a PR that adds a line for every language be good enough for you? That doesn't seem like a clean way to solve it...

**Comment by decabeza** [comment]
Hi @PierreMesure, the PR should have two parts: ☺️ 

- Adds a line for every language supported.
- Make that use the correct language when the locale change.
