### ISSUE TITLE
Make Milestones Polymorphic

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2763]
Context
===
Budget investments have [Milestones](https://github.com/consul/consul/pull/1688) to be able display the chronological order of events from becoming a winning investment to becoming an executed investment in real life

We would also like to add Milestone to [Proposals](https://github.com/consul/consul/issues/2740) and [Legislations](https://github.com/consul/consul/issues/2743)

What
===
- Make Milestones  [polymorphic](http://guides.rubyonrails.org/association_basics.html#polymorphic-associations)

How
===
- Creating a `Milestonable` Concern
- Adding it to Budgets
- Creating the corresponding rake tasks to migrate data from the now obsolete table `Budget::Investment::Milestone`

Update
===
Take into account the related migration from a `Budget::Investment::Status` to for example a `Milestone::Status`

**Comment by voodoorai2000** [comment]
Yes... that's the first thing that I thought too...
But it might make things a little more complicated than they have to be 🤔 

Maybe with a simple `milestone belongs_to :status` and a `status has_many :milestones` we are good to go 👍 https://github.com/consul/consul/issues/2743#issuecomment-404818820

**Comment by mlovic** [comment]
@voodoorai2000 Saw your other comment. Sounds good, I'll also replace `Budget::Investment::Status` with `Milestone::Status` then.

**Comment by mlovic** [comment]
@voodoorai2000 
Regarding:
> Creating the corresponding rake tasks to migrate data from the now obsolete table Budget::Investment::Milestone

I'm not sure how important availability is, but I'm assuming we need to do the following:

 1. create new tables (milestones + translations)
 2. copy data to new tables
 3. populate new `milestoneable_type` column with `"Budget::Investment"`
 4. deploy new code
 5. remove old tables

(Can we assume no writes will happen between 1 and 3?)

Should I create a migration file for 1, a Rake task for 2 and 3, and then a separate migration file for 5? Do we need separate PRs so that you can deploy one step at a time?

**Comment by voodoorai2000** [comment]
Great, yes that's pretty much it 😌
(I think 4 will have to be the first step though)

Availability is very important, but yes I think we can assume no writes will happen between 1 and 4

I would do 1-4 in this PR and include it in the upcoming release (right now 0.16)
And 5 in a separate PR and include it in the subsequent release (0.17) 👌

**Comment by voodoorai2000** [comment]
Closed via https://github.com/AyuntamientoMadrid/consul/pull/1698

**Comment by voodoorai2000** [comment]
Pending Backport to CONSUL
