### ISSUE TITLE
Spec fails when platform doesn't include Spanish as a language

### ISSUE THREAD

**Issue by PierreMesure** [consul/consul#2935]
### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)

```
1) Admin poll questions Poll select box uses fallback if name is not translated to current locale
     Failure/Error: expect(page).to have_select('poll_question_poll_id', options: [poll.name_es])
       expected to find visible select box "poll_question_poll_id" that is not disabled with options ["Nombre en Español"] but there were no matches. Also found "Name in English", which matched the selector but not all filters.
     # ./spec/features/admin/poll/questions_spec.rb:150:in `block (3 levels) in <top (required)>'
```
### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

You can check our [fork](https://github.com/digidemlab/consul) and the [spec report](https://travis-ci.org/digidemlab/consul/jobs/434100500).

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

**Comment by javierm** [comment]
@PierreMesure Thank you very much for this bug report! The spec causing the error assumes the application will configure the French language to fallback to Spanish. Since it's configured to fallback to English on your fork, it fails.

Probably the spec should not assume that much. We're having a look at it and will include a fix as part of AyuntamientoMadrid#1669.

**Comment by PierreMesure** [comment]
Good catch!

**Comment by javierm** [comment]
Hi @PierreMesure. We don't have a proper solution for it yet, since stubbing locales in tests is quite a pain, unfortunately.

In the meantime, you can try adding this code in your `spec/spec_helper.rb` file:

```ruby
  config.before do
    @i18n_default_locales = I18n.available_locales
    I18n.available_locales = I18n.available_locales + [:nl, :"pt-BR"]
    I18n.backend.send(:init_translations)

    ActiveRecord::Base.connection.tables.map { |table| table.classify.safe_constantize }.compact.each do |subclass|
      allow_any_instance_of(subclass).to receive(:globalize_locales).and_return(I18n.available_locales)
    end
  end

  config.after do
    I18n.available_locales = @i18n_default_locales
  end
```
It's an ugly hack and it might cause some other problems depending on your locales configuration (that's why we didn't include something similar in this release), but you can give it a try.

> I'm also a bit confused by the fact that you removed the list of locales for multi-language content (from `app/models/i18n_content.rb`) just before releasing. It seems you're using the list from `config/application.rb` now.

That's correct. Is it causing any problems?

**Comment by PierreMesure** [comment]
No problem at all, and I think that’s much better this way! I was just wondering because I couldn’t see anything in the update notes. Which makes sense since people using only the stable versions never had to deal with the local names in this file.

I think I’ll change the locale names in the specs, it might cause a few merging conflicts in the future but it’s better than slowing down the whole process or disabling them altogether.

Another suggestion: could we pass the locales we test with as variables? I’m not sure that’s doable (and it’s probably not good practice anyway) but an ideal solution would be for the test suite to run against the languages chosen.

**Comment by javierm** [comment]
> Another suggestion: could we pass the locales we test with as variables?

That's a very interesting idea. I'll have a look at it next time we're dealing with locales and specs.
