### ISSUE TITLE
Edited proposal gets "similar proposal" warning

### ISSUE THREAD

**Issue by PierreMesure** [consul/consul#2980]
### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

Really low priority but I thought this one was funny.

Try to edit a proposal, to change the title a bit. You will get the warning that a similar proposal exists. Thanks but it's the same...

![capture d ecran 2018-10-18 a 09 59 32](https://user-images.githubusercontent.com/7223028/47143635-e6f4e700-d2c5-11e8-88b0-47d5f3bdd4e6.png)

### Current Behavior
[comment]: # (Describe what actually happened.)

Warning

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

No warning

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

See above.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

The warning should never appear when you are editing a proposal, only when creating a new one.

**Comment by javierm** [comment]
I'm wondering whether we should disable this feature when editing a proposal :thinking:. Its purpose is to warn about similar proposals when creating a new one, but I'm not sure it makes sense once the proposal has already been created. The text even says "instead of creating a new [one]" :sweat_smile:.

@PierreMesure Any thoughts on this?

**Comment by javierm** [comment]
Closed by #4455.
