### ISSUE TITLE
Translate changes from proposals to legislation proposals

### ISSUE THREAD

**Issue by shak18** [consul/consul#3086]
### User Story

So, we made a fork of consul to implement in our goverment entity, and made some changes to the way proposals work, the problem here is that i dont want to find the easy way at the end , is there any recomended way to translate the changes from proposals to legislation proposals?

### Why is this Needed?

Because the theres the need of the proposals to behave the same way in proposal and legislation

### Description

Type: Feature

### Current Behavior
[comment]: After making changes and adaptation to proposals, the legislation proposals have a diferent way to work than regular

### Expected Behavior
[comment]: A way to translate behaviors so proposal and legislation proposals behave the same way after changes in one or the other

**Comment by javierm** [comment]
@shak18 Sorry for the late reply! :pray:

This is indeed a big flaw in the design of legislation proposals: the code was copied from proposals and is hard to maintain.

At some point this part of the code will need some refactoring :thinking:. In the meantime, there's no specific way to deal with this problem, other than general principles when working with legacy/duplicate code. Try to write new code in a way that both proposals and legislation proposals can reuse it.

It looks like this issue is very similar to #2675. Do you mind if I close this one and we continue the conversation there, so we've got all related comments in one place? Feel free to reopen this issue if you feel I'm wrong and these two issues are different! :smile:
