### ISSUE TITLE
Specifing starting/ending time instead of only dates in polls

### ISSUE THREAD

**Issue by adundovi** [consul/consul#4133]
### User Story

I think there is a reasonable user case in which one should control the starting/ending time when creating a poll, not only dates.

### Why is this Needed?

For example, for short duration polls, one would run them for the whole day until 7 PM and at 8 PM release the results. Or, since the results can only be checked after the poll is finished, one would like to run a test poll for a brief period just to check if everything works as expected.

### Description

It's a trivial feature to implement, I believe as the time is already stored in the DB.

**Comment by javierm** [comment]
@adundovi Thanks for the suggestion! :smile:

Unfortunately it isn't that trivial to implement due to the [lack of browser support for datetime-local input fields](https://caniuse.com/mdn-html_elements_input_input-datetime-local) and lack of a standard calendar+hour widget which we could use for browsers not supporting this input type.

Feel free to open a pull request if you find a solution providing a good user interface and which is compatible with our exsting code :wink:.

**Comment by javierm** [comment]
Looks like both Safari and Firefox have added support for this element in 2021. Combined with the fact that a year has gone by since the last update, now at least [76.6% of the browsers support this field](https://caniuse.com/mdn-html_elements_input_input-datetime-local), so I think it makes sense to add this input and provide a date field as a fallback :thinking:.

We'll have a look at it :+1:.
