### ISSUE TITLE
Add "target" to allowed_attributes of AdminWYSIWYGSanitizer

### ISSUE THREAD

**Issue by Michael1337** [consul/consul#4223]
### Description
When an admin creates a custom page, they can add links to other web sites and choose a target setting like "_blank". However, this target setting is currently lost during the sanitizing process.

### Current Behavior
The only allowed attributes are: [href] + [alt src align border cellpadding cellspacing dir style class summary scope id]

### Expected Behavior
The target attribute should be included: [href] + [alt src align border cellpadding cellspacing dir style class summary scope id target]
"rel" or other attributes might need to be added as well.

### Steps to reproduce
1. Got to https://demo.consulproject.org/admin/site_customization/pages.
2. Choose a page and edit it.
3. Add a link to any word, choose any URL like google.com, go to "target" and choose for example "_blank". Save the Change.
4. Go to the custom page and click on the new link.

**Comment by javierm** [comment]
Hi, @Michael1337 :smile:.

We're currently thinking about doing the opposite: removing the "target" tab and reducing the amount of `target="_blank"` uses in the application. Opening links in new tabs/windows causes several usability issues (see [Jakob Nielsen on opening links in new windows and tabs](https://www.nngroup.com/articles/new-browser-windows-and-tabs/) or [when to use target="_blank"](https://css-tricks.com/use-target_blank/)), and so its use should be very limited :thinking:.

**Comment by Michael1337** [comment]
Hi @javierm ,

thank you for your replies! :)
We currently open new tabs for external PDF files and don't want the readers to get lost. I do agree with your provided articles (thanks!) in that it is not necessary to open those links in new tabs, but I still got to admit: I, personally, will always open them in a new tab to make it easier to remember how and why I got there, and I want the same for our users who may not know how to open links in new tabs manually.
I think removing the target feature is a rather frustrating approach. At least my supervisors would then ask me why they can not make links open in new tabs and would make me implement it for them 😅 Maybe we can encourage administrators to use the feature less while still enabling them to do so, for example by providing a short information text on best practices in the target tab.

**Comment by javierm** [comment]
Hi, @Michael1337.

Regarding external PDFs, it depends on the brower and its configuration. In my case, for instance, I get lost when the PDF is opened in a new tab, since a new blank tab opens and then I'm asked whether I'd like to save or open the file, wondering what the new blank tab was about.

In the end, we cannot predict the behavior users are going to prefer, so keeping them in control of the way their browsers behave is IMHO the best we can do.

> At least my supervisors would then ask me why they can not make links open in new tabs and would make me implement it for them

I undestand :relieved:. In the past, in this situation I used to tell my then-supervisors that automatically opening links in new tabs is generally a bad idea and explain the reasons why. Sometimes they said "you're the expert" and agreed, and sometimes they kept on insisting and I did what they asked for.

If your case is the latter, you can always change the source code and add "target" to the list of allowed attributes :thinking:.

We might change our minds in the future, but for now, we're going to try to reduce (or, at least, stop increasing) the usability issues we've got due to opening links in new tabs.

**Comment by Michael1337** [comment]
Hi @javierm ,

thanks again for your thorough explanation. For now, I actually did just do what I suggested with the title of this issue. So I guess I will just copy the old code in case the admin interface will get changed to remove the target tab. Or I will send the link to this issue to my supervisors, especially this bit: 

> In the end, we cannot predict the behavior users are going to prefer, so keeping them in control of the way their browsers behave is IMHO the best we can do.

👍
