### ISSUE TITLE
Demo: improving English

### ISSUE THREAD

**Issue by Pomerange** [consul/consul#4737]
### User Story

As a potential user, I'd like to see what Consul does by entering the demo. Would be nice to have slightly improved English in some cases, mostly in the use of prepositions or adverbs. This is from the verified user perspective.

### Why is this Needed?

In research of which FLOSS or participation platform to use, I expect people to research what's available. Updating some of the texts will help make it look more professional.

### Description

_Homepage_
Highlight: Vote **on** the participatory budget --> budget and not budgeting
Featured: Comment **on** / Decide **on**

_Debates_
Help about debates --> Help **with** debates
Supports --> Support (supports doesn't exist in the plural, like vote/votes)

_Proposals_
Help about proposals --> Help **with** proposals
Proposals retired? --> Could you mean **withdrawn** proposals? I am not sure what this refers to.

_Voting_
Help with (see above)

_Collaborative Legislation_
Help with (see above)

_My account_
Change my credentials --> Change my account details _OR_ Change my login details (credentials is something like qualifications, high-school diploma, academic degree)
Participation: With your account you can participate **in** debates
Participation: Participate **in** final voting. What is meant here with final voting?
Notifications: Receive by email website relevant information --> Receive relevant information by email.
Recommendations: Recommend debates / proposals to me_OR_ Show recommendations for debates / proposals _OR_ show recommended debates / proposals. 

All minor things, but might help cleaning some things up.

**Comment by amanintech** [comment]
I can work on a fix for this

**Comment by javierm** [comment]
@amanintech Thanks! :pray: Go ahead :smile:.

Just one thing, though:

>  Footer: For technical assistance visit .... (blank)

Ignore this one :wink:, since it's already being addressed in pull request #4731.

**Comment by javierm** [comment]
Hi, @amanintech :smile:. Are you still working on this issue?

**Comment by javierm** [comment]
@amanintech I've just opened pull request #4802 to address this issue. Hope you don't mind!

**Comment by javierm** [comment]
@Pomerange Some comments about the suggested changes:

> Homepage
> Highlight: Vote on the participatory budget --> budget and not budgeting
> Featured: Comment on / Decide on

These texts aren't included in CONSUL and are only available in the demo. I've just updated the demo; starting tomorrow, the new texts should be displayed.

>  Supports --> Support (supports doesn't exist in the plural, like vote/votes)

That might be right, but I'm not sure texts like "200 support needed" makes sense either :thinking:, since in this context "support" seems to be an uncountable noun :thinking:.

> Proposals retired? --> Could you mean withdrawn proposals? I am not sure what this refers to.

Definitely withdrawn. In Spanish, "retirar" means both "retire" and "withdraw", so it was probably a literal translation.

> Change my credentials --> Change my account details OR Change my login details (credentials is something like qualifications, high-school diploma, academic degree)

Credentials [might also refer to login/password](https://www.pcmag.com/encyclopedia/term/login-credentials), although I've no idea about how many people prefer this term over "login details" or similar. Whatever you say is fine with me :wink:.

> Participation: Participate in final voting. What is meant here with final voting?

It seems to refer to the "balloting/voting" phase during a participatory budget. Feel free to suggest a better name!

**Comment by amanintech** [comment]
> @amanintech I've just opened pull request #4802 to address this issue. Hope you don't mind!

absolutely, I feel terrible on not being able to get back on this

**Comment by javierm** [comment]
@amanintech No problem! :wink: Thank you for your interest in contributing to CONSUL and, should you find more typos, issues reporting them or pull requests fixing them are welcome :smile:.

**Comment by Pomerange** [comment]
Hi, thanks for checking my suggestions. I agree with all your changes. 
As to offer a decision for some open questions
- Change my login details
- let's leave supports for now
- Participate in final voting: Vote for budget projects

**Comment by javierm** [comment]
@Pomerange Cool, thanks!

Since we're at it, we're also removing the "* Only for users on Census." text in "my account", since there are no items with an asterisk (although there are items with an asterisk in the Spanish version) and we're already specifying what people can/can't do with their account and showing a link to verify it when they can't do certain things.
