### ISSUE TITLE
Admin should always be able to see poll results

### ISSUE THREAD

**Issue by tonekk** [consul/consul#4771]
### User Story

As an admin, I always want to be able to see poll results - not just for polls that are expired.

### Why is this Needed?

Our client was wondering why they couldn't see any results, although they were logged in as admin.
I personally also think this behaviour is not what I would expect.

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*:

### Current Behavior
Admin can only see results of expired polls (like everyone else)

### Expected Behavior
Admin can see results of all polls at all times

### Steps to reproduce
* Create poll
* Vote
* Go to `/polls/:poll-slug/results`
* You will get redirected to Home

### References

 #3964

**Comment by javierm** [comment]
Hi, @tonnek :smile:.

I'm afraid we aren't going to implement this feature. Allowing governments to see the results while the poll is still open might allow them to take measures when the poll isn't going the way they wanted.

I understand CONSUL is used by different kinds of institutions and there might be cases where this functionality makes sense. However, due to the dangers associated to it, we can't add it. Hope that's OK!

**Comment by javierm** [comment]
Hi, @tonekk :smile:.

I'm afraid we aren't going to implement this feature. Allowing governments to see the results while the poll is still open might allow them to take measures when the poll isn't going the way they wanted.

I understand CONSUL is used by different kinds of institutions and there might be cases where this functionality makes sense. However, due to the dangers associated to it, we can't add it. Hope that's OK!

**Comment by tonekk** [comment]
I understand - I was already kind of anticipating this answer :)

**Comment by javierm** [comment]
> Technically though, if they host it, they WILL be able to see the results.

That's 100% true. If it were feasible to implement a way so digital votes behave like closed envelopes and can only be opened once the poll has finished, we would do so (this is also related to issue #2135). In the meantime, at least we don't make it _that_ easy to check the results :smile:.
