### ISSUE TITLE
What are Proposal-related-Polls used for?

### ISSUE THREAD

**Issue by tonekk** [consul/consul#4772]
Hi,

I have a question. As a user I can create a `Poll` under the `Proposal` Dashboard.
Those Polls can't be found under the `PollsController#index` page, and there is also no link to be found on the proposals page.

My question now is: What are these Polls used for? How would I access them as a normal user? By sending the link?

Thanks

**Comment by javierm** [comment]
Hi, @tonekk :smile:.I guess the intention was to use the "Message to users" feature in the dashboard and notify the followers about the poll :thinking_face:. Can't say for sure; unfortunately the dashboard feature is arguably the least polished feature in CONSUL and the original authors are no longer involved with the project, so we're currently discussing what to do about it.

So, as you mentioned, normal users can only access the poll if the author sends them the link.

**Comment by karim-semmoud** [comment]
Hi tonekk,
**What are these Polls used for ?**
First there the main "Voting" section, only admin can create "polls" in the admin section and there can be found and searched for under /polls
Then there is "Surveys" that every users can create for your own proposal  under the "dashboard poll" section
They are different because the second one is specific to a single proposal and everyone can create one. They cannot be found in the main " Voting" section.

**How would I access them as a normal user?**
1-As user create a Proposal and publish it
2-Go to the dashboard of this proposal and create a poll plus a questions & answers. Please note that only one poll can be active at the same time. There is also an option to make the poll results public.
3-As another user , visit the Proposal page you have created previously
4-Select access the community
5-Select "Participate to this Survey"
6-Here you can see the poll the same way than the main polls created by an Admin

To resume the polls created by users for the proposal dashboard are not found in the "Voting" of the site but in the "Community" section related to each proposals and are publicly called "Survey"

I hope this helps
![Screenshot from 2023-04-15 11-32-55](https://user-images.githubusercontent.com/114252883/232205768-54d9d60f-5f04-4259-99e1-dec36795ad8c.png)

**Comment by javierm** [comment]
@karim-semmoud Thank you for your reply! :pray: I completely forgot you could access these pages through the community page.

@tonekk Closing this issue since it seems to me that the question is already answered, but feel free to reopen if that isn't the case :wink:.
