### ISSUE TITLE
how to configure mailing

### ISSUE THREAD

**Issue by RamzuYunus** [consul/consul#4984]
Hi. I cant seem to get the mailing configuration correct as the system is not sending emails. Is there an example of the following configuration filled in? I think I may be filling in the wrong things.

  mailer_delivery_method: :smtp
  smtp_settings:
     :address: "<smtp address>"
     :port: 587
     :domain: "<domain>"
     :user_name: "<user_name>"
     :password: "<password>"
     :authentication: "plain"
     :enable_starttls_auto: true

**Comment by javierm** [comment]
Hi, @RamzuYunus.

Just in case, note that you need to restart the Rails application after changing the `config/secrets.yml` file; otherwise, the changes won't be applied.

You can see an example at [Configure ActionMailer to Use SendGrid](https://docs.sendgrid.com/for-developers/sending-email/rubyonrails#configure-actionmailer-to-use-sendgrid). Note that they add the settings to the `environment.rb` file but, in CONSUL, you should use the `config/secrets.yml` file instead.

Hope that helps!
