### ISSUE TITLE
Help embedding pol.is into a consul page

### ISSUE THREAD

**Issue by robgitnyc** [consul/consul#5010]
Hello.

I would like to be able to embed a pol.is wikisurvey. It's a simple html snippet:

```
<div
  class='polis'
  data-page_id='PAGE_ID'
  data-site_id='polis_site_id_aIazSTsbqqZO8466u0'>
</div>
<script async
  src='https://pol.is/embed.js'>
</script>
```
However, since the page creation page in Consul doesnt allow html, I would like to know where exactly should I add this html code in order to be able to integrate into consul.

Your help will be much appreciated. 

edit: i tried editing the appropriate cell in site_customization_page_translations in database but it ignores all html tags (except a few basic ones)

**Comment by javierm** [comment]
Hi, @robgitnyc :smile:.

As you've noticed, `<script>` tags are automatically removed for security reasons. In order to enable them, you'll have to change the source code of the application; in particular, the `lib/admin_wysiwyg_sanitizer.rb`. There you can add `script` to the list of allowed tags.

Also note that, if that script uses third-party cookies (I don't know whether that's the case), you might need to update the application to make sure users accept those cookies.

Hope that helps!
