### ISSUE TITLE
Header Images with brackets in title are not displayed.

### ISSUE THREAD

**Issue by TomClive** [consul/consul#5051]
Hi - we're experiencing issues with banner images. We noticed that if any of the images contain brackets in the title they do not display.

This image is accepted for upload,

![image](https://user-images.githubusercontent.com/9372488/208407027-cd37053a-d8c9-4da5-9bbf-1664c281ae1d.png)

But does not display.

![image](https://user-images.githubusercontent.com/9372488/208406767-11e3abbb-fb45-4d6a-ab55-9c82004e0d65.png)

Removing the brackets resolves the issue.

This does not appear to be the case with images in other areas of the site like the images displayed on cards.

Are the brackets not being escaped when displaying banner images? Could this be resolved (preferable) or a warning applied when the image is uploaded?

**Comment by javierm** [comment]
Hi, @TomClive :smile:.

I can confirm the issue. Thanks for reporting! Looks like we can use quotes around the image name to escape the brackets, but then images with quotes in their names wouldn't be rendered. Will have a look.

**Comment by karim-semmoud** [comment]
Hi @TomClive 

In app/components/budgets/budget_component.html.erb 
Adding single quotation marks '   '  around the url seems to work
```
<div class="budget-header with-background-image"
       style="background-image: url('<%= polymorphic_path(budget.image.variant(:large)) %>');">
```
instead of
```
<div class="budget-header with-background-image"
       style="background-image: url(<%= polymorphic_path(budget.image.variant(:large)) %>);">
```
The URL stays the same but background image is visible
![Screenshot from 2023-04-19 20-07-34](https://user-images.githubusercontent.com/114252883/233162845-bd44129b-4474-4a4a-bcef-d51d733ffa5b.png)
![Screenshot from 2023-04-19 20-07-18](https://user-images.githubusercontent.com/114252883/233162852-c099cad4-cb4e-4bc9-8723-86b687b12819.png)
