### ISSUE TITLE
 Users with official email

### ISSUE THREAD

**Issue by xuanxu** [consul/consul#717]
New feature: Users that sign up with an official/governmental email account (example: @madrid.es for Madrid) should be marked automatically as level 1 officials (the email domain should be customized by the admins).

Suggestions:
Add a rake task to convert the already existent users
Add a Settings entry for email_domain_for_officials

**Comment by xJakub** [comment]
Is anyone working on this? I would like to do this one.

**Comment by xuanxu** [comment]
@xJakub all yours! :)

**Comment by xJakub** [comment]
I had programmed the auto-assignment, the rake task and a spec to test the first one. However, the following specs were then broken:
rspec ./spec/models/user_spec.rb:227 # User officials scope returns only users with official positions
rspec ./spec/features/stats_spec.rb:45 # Stats Summary Users
rspec ./spec/features/admin/officials_spec.rb:68 # Admin officials Destroy
rspec ./spec/features/admin/officials_spec.rb:12 # Admin officials Index

In order to avoid conflict, I set the default value for email_domain_for_officials to 'empleados.madrid.es', which can be changed from the administration panel. However, right now the code grants the official level (official_position is set to Empleados públicos) before the user confirms the mail address. Should it be granted only after confirming the address?

**Comment by xuanxu** [comment]
Yes, the official level should be assigned once the email is confirmed, a good point is after first login, for example. 
And another detail: it's a optional feature, so there should not need a 'default' email domain, everything should work if no domain is specified by the admins.

**Comment by Ana06** [comment]
I think it is done

**Comment by voodoorai2000** [comment]
Indeed!

Closed via #740
